source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'xxcolor' do
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'UMengAnalytics-NO-IDFA'
  pod 'SnapKit', '~> 3.2.0'
end
